### ISSUE TITLE
Windows 11 PermissionError: [Errno 13] Permission denied🐛

### ISSUE THREAD

**Issue by odd86** [policratus/pupyl#195]
**Describe the bug**
Following the example in the documentation, I struggle with making an Index.
Hopefully it's an rookie mistake, but I have checked file permissions and everything seems to be ok (possible to manipulate and load files in other code)

**To Reproduce**
Make a new project, and have a folder inside with .jpg images.

Try to run:

```
import os

from pupyl.search import PupylImageSearch

# This will create pupyl database on the current directory, inside a
# directory called 'pupyl'
PUPYL = PupylImageSearch(data_dir=os.path.join(os.curdir, 'pupyl'))

PUPYL.index('Z:\\pokemon')
```

**Expected behavior**
That the images inside the folder are indexed.
The library are able to create the folder 'pupyl' 

**Desktop (please complete the following information):**
 - Windows 11 Python 3.11

--

Thanks a lot for any help :)

**Comment by policratus** [comment]
Hey @odd86, thanks for reporting this.

We are working right now to get better Windows support (through #169), specially regarding the differences in the filesystem compared to Linux and MacOS.

What we saw when a `PermissionError: [Errno 13] Permission denied` happens is related to some weird permissions (and access check) that the Windows default temporary directory needs and this is not well addressed in `python` (as we can check on this decade-long `cpython` issue: https://github.com/python/cpython/issues/66305), but isn't that hard to circumvent this. Since `pupyl` uses the underlying temporary directory for some internal processes, this is the reason why this issue happens even without any direct `temp_dir` access by the user.

We hope to come back to this issue in the next couple of weeks and let you (and community) know the advancements on this.

And thank you for using `pupyl`!
