### ISSUE TITLE
🐛 Searching Using Local File URI

### ISSUE THREAD

**Issue by mastreips** [policratus/pupyl#99]
I can't get the web search engine to properly recognize local file uris (file://) searches.  I can retrieve the local URI in the browser, but when I use that same URI in the Pupyl Web Interface Search Bar, I get a "File or Directory not found" error.  What is the proper way of searching the index using local files (not http addresses)? Thanks!

**Comment by policratus** [comment]
Hey @mastreips, thanks for reporting this. This will fixed after closing pull request #101 and will be part of next `pupyl`'s version, `0.12.2`.

Before, wasn't possible to use local files (through the web interface) as query images because most browsers avoids local files references on `HTML` due to [security issues](https://stackoverflow.com/questions/4090712/why-cant-i-do-img-src-c-localfile-jpg). Since `pupyl`'s web interface is really simple, intended only for visualization (not to go to production) and uses internal (native) `python` simple [http.server](https://docs.python.org/3.8/library/http.server.html) (which also is not intended to production environments) to mitigate adding new (and external) dependencies, the workaround used on the web interface to be able to show image file under `file://` schemes is proposed on pull request #101.

After closing #101, this will be possible:

![Screenshot from 2021-08-23 16-31-32](https://user-images.githubusercontent.com/827563/130508042-df450c71-7fa8-4ede-afe9-811f0d026967.png)

Searching local files using the API was already supported, as in:

```Python
from pupyl.search import PupylImageSearch
SEARCH = PupylImageSearch()
SEARCH.search('/path/to/you/local/file.jpg')
```

Pull request #101 also adds support to search using local files as below:

```Python
SEARCH.search('file:///path/to/you/local/file.jpg')
```
